[package]
name = "phonewords"
version = "0.0.8-3"
authors = [
    "Christopher Welborn <cj@welbornprod.com>",
    "Thomas Bahn <thomas@thomas-bahn.net>"
]

[dependencies]
itertools = "*"

[dependencies.clippy]
git = "https://github.com/Manishearth/rust-clippy"
